name: Deploy Kong Dev

on:
  workflow_dispatch:
  
  push:
    branches: 
      - "feature-dev"
jobs:
  deploy:
    uses: ForgeCrux/pipeline-template/.github/workflows/kong.yaml@main
    permissions:
      contents: read
      id-token: write
    with:
      environment: dev
      kong_config_path: kong/dev/kong.yaml
      control_plane_name: Forgeshiftw2k
      validate_only: false
      
    secrets:
      konnect_token: 'kpat_HPfFTlLKMFheS5l2ifywp7fERjXadKWohLWSjem90dcdtbf8B'
